const q=(text,options,answer,rationale,level='Understanding',difficulty='Moderate')=>({text,options,answer,rationale,level,difficulty});
const S=(title,focus,ideas,examples,tool)=>({title,focus,ideas,examples,tool});
const W=(week,theme,sessions)=>({week,theme,sessions});
const COURSE={title:'Mathematics in the Modern World',basis:'CHED-guided Mathematics in the Modern World module; CMO No. 20, series of 2013',weeks:[
W(1,'Course Introduction and Mathematical Language',[
 S('Course Introduction: Mathematics in the Modern World','Explain the scope of CGE103 and recognize mathematics as a language for patterns, relationships, quantities, and decisions.',['Course scope and expectations','Mathematics beyond calculation','Patterns in daily life','Representation and mathematical communication','Responsible reasoning and verification'],['A timetable represents relationships among time, distance, and activity.','A budget uses quantities to support decisions.','A pattern must be described and checked before it is generalized.'],'Orientation activity: identify mathematics used in one ordinary day and explain the information, pattern, or decision involved.'),
 S('Patterns and Mathematical Language','Recognize patterns and translate everyday relationships into clear mathematical symbols and statements.',['Patterns and regularities','Variables and symbols','Expressions and equations','Equality and relationships','Precision in mathematical language'],['“Three more than a number” becomes x+3.','₱250 per person becomes C=250n.','A map scale connects drawing distance with actual distance.'],'Translation activity: write everyday statements in words and symbols, then explain the meaning of each variable.')]),
W(2,'Recognizing Patterns and Sequences',[
 S('Recognizing and Generalizing Patterns','Move from observing visual and numerical patterns to expressing a defensible general rule.',['Visual and numerical patterns','Term position and term value','Constant differences','Recursive descriptions','Explicit descriptions'],['4, 7, 10, 13 has a common difference of 3.','A growing tile design adds one border layer per stage.','A seating row that gains two chairs can be represented by a linear rule.'],'Create a table of term number and term value, describe the change, and test the proposed rule on another term.'),
 S('Sequences and the Fibonacci Pattern','Analyze arithmetic, geometric, and Fibonacci-type sequences without overstating their occurrence in nature.',['Arithmetic sequences','Geometric sequences','Fibonacci recurrence','Ratios of consecutive terms','Responsible pattern claims'],['5, 9, 13, 17 is arithmetic.','3, 6, 12, 24 is geometric.','1, 1, 2, 3, 5 uses the previous two terms.'],'Use spreadsheet formulas to extend sequences, graph their terms, and compare how rapidly they grow.')]),
W(3,'Visual Patterns, Symmetry, and Fractals',[
 S('Visual Patterns and Symmetry','Classify transformations and symmetry in designs, objects, and cultural forms.',['Reflection symmetry','Rotational symmetry','Translation','Tessellation','Symmetry as mathematical structure'],['A bilateral leaf approximates reflection symmetry.','A four-blade fan has rotational symmetry of order four.','A repeated floor tile illustrates translation.'],'Use a diagram or GeoGebra to reflect or rotate a figure and compare corresponding points.'),
 S('Fractals and Growth Patterns in Nature','Explain self-similarity, iteration, and scaling in mathematical and natural patterns.',['Self-similarity','Iteration','Scale changes','Fractal dimension as an extension','Natural forms as approximate fractals'],['The Sierpiński triangle repeats a removal rule.','Fern leaflets approximately resemble the larger frond.','Coastline measurement changes with ruler length.'],'Construct successive stages of a Sierpiński triangle and record how the number and size of pieces change.')]),
W(4,'Problem Solving and Reasoning',[
 S('Inductive and Deductive Reasoning','Use inductive evidence and deductive logic appropriately when forming and justifying conclusions.',['Inductive generalization','Deductive conclusion','Conjecture and counterexample','Premises and validity','Evidence is not proof'],['Observed cases can suggest but not prove a universal rule.','One counterexample disproves a universal claim.','All multiples of 4 are even; 28 is a multiple of 4; therefore 28 is even.'],'Classify short arguments as inductive or deductive, identify premises, and test universal claims with counterexamples.'),
 S('Polya’s Four-Step Problem-Solving Method','Solve unfamiliar problems by understanding, planning, carrying out, and looking back.',['Understand the problem','Devise a plan','Carry out the plan','Look back and verify','Use diagrams, tables, patterns, and simpler cases'],['Draw a diagram before solving a route puzzle.','Organize possible cases in a table instead of guessing.','Check the answer against the original conditions and units.'],'Complete Given, Asked, Representation, Plan, Solution, and Check for one contextual problem.')]),
W(5,'Patterns and Recreational Problem Solving',[
 S('Mathematical Problems Involving Patterns','Use Polya’s method with tables, diagrams, sequences, and generalization.',['Recognize relevant patterns','Organize cases','Find a rule','Test the rule','Explain and verify'],['A handshake table reveals triangular-number growth.','A matchstick figure can be modeled by term number.','A counterexample can expose a false pattern rule.'],'Solve one growing-pattern problem.'),
 S('Recreational Problems Using Mathematics','Develop strategic reasoning through puzzles, games, and number problems.',['Work backward','Make an organized list','Eliminate impossible cases','Use invariants','Verify uniqueness'],['A river-crossing puzzle requires legal moves.','A magic square has equal row, column, and diagonal sums.','A game strategy can rely on parity.'],'Solve and explain a recreational puzzle.')]),
W(6,'Modular Arithmetic Fundamentals',[
 S('Clock Arithmetic and Congruence','Model repeating cycles and interpret congruence modulo n.',['Remainders','Clock arithmetic','Congruence modulo n','Residue classes','Addition tables'],['15 o’clock is 3 on a 12-hour clock.','17≡2 (mod 5).','Modulo n uses residues 0 through n−1.'],'Construct and use a modulo addition table.'),
 S('Properties and Addition Tables','Apply equality, congruence properties, and addition tables in modular systems.',['Reflexive property','Symmetric property','Transitive property','Compatibility with operations','Modulo n addition tables'],['Every integer is congruent to itself modulo n.','If a≡b, then b≡a.','A table shows every possible sum of residue classes.'],'Complete and interpret a modulo table.')]),
W(7,'Operations on Modular Arithmetic',[
 S('Addition and Subtraction Modulo n','Reduce sums and differences to standard residues.',['Modular addition','Modular subtraction','Negative residues','Equivalent residues','Clock applications'],['8+9≡5 (mod 12).','2−7≡0 (mod 5).','−1≡4 (mod 5).'],'Solve cyclic schedule and clock problems.'),
 S('Multiplication and Powers Modulo n','Compute modular products and powers efficiently.',['Modular multiplication','Repeated multiplication','Modular powers','Reduction during computation','Patterns in powers'],['3×4≡2 (mod 5).','2⁴≡1 (mod 5).','Large values may be reduced before operating.'],'Find patterns in powers modulo n.')]),
W(8,'Applications of Modular Arithmetic',[
 S('Check Digits and Identification Numbers','Use modular tests to verify UPC, ISBN, and other identification codes.',['Weighted sums','Check digits','UPC validation','ISBN validation','Detection limitations'],['A weighted remainder determines a check digit.','A valid check digit detects many entry errors.','Passing a check does not prove authenticity.'],'Verify sample product and book codes.'),
 S('Encryption and Decryption','Apply modular arithmetic to simple coding and decoding systems.',['Plaintext and ciphertext','Alphabet-number mapping','Caesar shift','Encryption rule','Decryption rule'],['A Caesar shift adds a key modulo 26.','Decryption subtracts the same key.','Weak ciphers preserve language patterns.'],'Encrypt and decrypt a short message.')]),
W(9,'Group Theory',[
 S('Groups and Their Properties','Determine whether a set and operation satisfy the group axioms.',['Closure','Associativity','Identity','Inverse','Abelian groups'],['Integers under addition form an abelian group.','Natural numbers under addition lack inverses.','A group need not be commutative.'],'Test small systems against the group axioms.'),
 S('Symmetry and Group Applications','Connect transformations and repeated designs with group operations.',['Symmetry transformations','Composition','Identity transformation','Inverse transformation','Finite symmetry groups'],['Two reflections can combine into a rotation.','Doing nothing is the identity transformation.','Undoing a rotation uses its inverse.'],'Analyze the symmetries of a simple figure.')]),
W(10,'The Data',[
 S('Data, Variables, Sampling, and Presentation','Classify data, evaluate collection methods, and organize observations.',['Population and sample','Qualitative and quantitative data','Levels of measurement','Sampling and bias','Frequency distributions'],['Course is categorical while age is numerical.','A convenience sample may be biased.','A frequency table summarizes repeated values.'],'Classify and tabulate a small data set.'),
 S('Organizing and Presenting Data','Construct frequency tables and appropriate visual displays.',['Raw and arrayed data','Class intervals','Frequency distributions','Bar graphs and histograms','Honest labels and scales'],['Class intervals must not overlap.','Histograms display numerical distributions.','A misleading axis can exaggerate differences.'],'Organize one data set and select a suitable graph.')]),
W(11,'Measures of Central Tendency',[
 S('Mean, Median, and Mode for Ungrouped Data','Compute and interpret the common measures of center.',['Arithmetic mean','Median','Mode','Outliers','Choosing an appropriate center'],['Median resists an extreme outlier.','The mean uses every observation.','A set may have more than one mode.'],'Compare measures of center for one data set.'),
 S('Central Tendency for Grouped and Weighted Data','Estimate center from grouped data and calculate weighted means.',['Grouped-data mean','Class midpoint','Grouped median','Modal class','Weighted mean'],['A midpoint represents values in a class.','A weighted mean reflects unequal contributions.','Grouped results are estimates.'],'Calculate a grouped or weighted mean.')]),
W(12,'Measures of Dispersion',[
 S('Measures of Dispersion','Compute and interpret range, variance, standard deviation, and coefficient of variation.',['Range','Variance','Standard deviation','Coefficient of variation','Comparing variability'],['A larger standard deviation means greater spread.','Two sets may have equal means but different variability.','CV compares relative spread across scales.'],'Compute and compare dispersion.'),
 S('Interpreting and Comparing Variability','Use standard deviation and coefficient of variation to compare data sets.',['Spread around the mean','Population and sample formulas','Units of standard deviation','Relative variability','Consistency'],['Lower spread indicates more consistency.','Variance uses squared units.','CV is useful when means or units differ.'],'Compare the consistency of two groups.')]),
W(13,'Relative Position and Normal Distribution',[
 S('Measures of Relative Position','Locate observations using quartiles, deciles, percentiles, and z-scores.',['Quartiles','Deciles','Percentiles','Interquartile range','Standard score'],['Q2 is the median.','The 80th percentile has 80% at or below it.','A positive z-score lies above the mean.'],'Find and interpret relative-position measures.'),
 S('The Normal Distribution','Use the normal curve and standard scores to describe probabilities and positions.',['Normal curve','Mean and standard deviation','Empirical rule','Standard normal distribution','Areas and probabilities'],['About 68% lies within one standard deviation.','The curve is symmetric about the mean.','A z-score converts values to a common scale.'],'Convert values to z-scores and interpret areas.'),
 ]),
W(14,'Correlation and Regression',[
 S('Linear Correlation: Pearson r','Measure and interpret the direction and strength of a linear relationship.',['Scatterplots','Positive and negative association','Pearson correlation coefficient','Strength and direction','Correlation is not causation'],['r near 1 indicates strong positive linear association.','r near 0 may hide a nonlinear relation.','A lurking variable can explain an association.'],'Create a scatterplot and interpret r.'),
 S('The Least-Squares Regression Line','Fit and interpret a linear prediction model and evaluate its limitations.',['Explanatory and response variables','Slope and intercept','Least-squares line','Prediction and residual','Interpolation and extrapolation'],['Slope gives predicted change per input unit.','A residual is observed minus predicted.','Extrapolation beyond the data range is risky.'],'Fit data and make a justified prediction.'),
 ]),
W(15,'Logic Statements, Quantifiers, and Truth Tables',[
 S('Logic Statements and Quantifiers','Translate statements into symbols and negate quantified statements correctly.',['Statements and truth values','Simple and compound statements','Connectives','Universal quantifier','Existential quantifier'],['A command is not a statement.','“All” is negated by “at least one not.”','“Some” is negated by “none.”'],'Symbolize and negate statements.'),
 S('Truth Tables, Equivalence, and Tautology','Construct truth tables and identify equivalent, tautological, and contradictory forms.',['Truth tables','Negation and connectives','Logical equivalence','Tautology','Contradiction'],['p∨¬p is a tautology.','p∧¬p is a contradiction.','Equivalent forms match in every row.'],'Construct and compare truth tables.'),
 ]),
W(16,'Digital Logic and Conditional Statements',[
 S('Switching Networks and Logic Gates','Model switching circuits with logical connectives and gate diagrams.',['Open and closed switches','Series and parallel networks','AND, OR, and NOT gates','NAND and NOR gates','Circuit truth tables'],['Series switches model AND.','Parallel switches model OR.','A NOT gate reverses the input.'],'Translate among statements, tables, and circuits.'),
 S('Conditional and Related Statements','Analyze conditionals, converses, inverses, contrapositives, and biconditionals.',['Conditional statement','Converse','Inverse','Contrapositive','Biconditional'],['p→q is equivalent to ¬q→¬p.','The converse need not equal the original.','A biconditional requires both directions.'],'Write and compare all related forms.'),
 ]),
W(17,'Symbolic Arguments and Graph Fundamentals',[
 S('Symbolic Arguments and Validity','Translate arguments and determine validity using rules or truth tables.',['Premises and conclusion','Modus ponens','Modus tollens','Valid and invalid forms','Soundness'],['Affirming the consequent is invalid.','A valid argument may have a false premise.','Soundness requires validity and true premises.'],'Test symbolic and everyday arguments.'),
 S('Graphs and Graph Models','Represent real situations with vertices, edges, degrees, paths, and connected graphs.',['Vertices and edges','Adjacency and incidence','Degree','Paths and circuits','Connected graphs'],['Locations can be vertices and roads can be edges.','Degree counts incident edges.','A graph model keeps connection structure while ignoring shape.'],'Convert a real network into a graph model.')]),
W(18,'Eulerian Graphs, Routes, and Coloring',[
 S('Graphs, Eulerian Circuits, and Route Problems','Model networks and solve Euler, postman, and economical-route problems.',['Vertices and edges','Degree and connectedness','Euler paths and circuits','Weighted graphs','Route algorithms'],['Exactly two odd vertices allow an Euler path.','All-even degrees allow an Euler circuit.','Weights can represent distance or cost.'],'Model and solve a route network.'),
 S('Graph Coloring and Scheduling','Determine chromatic numbers and apply graph coloring to conflicts and schedules.',['Adjacent vertices','Proper coloring','Chromatic number','Conflict graphs','Scheduling applications'],['Adjacent regions need different colors.','A timetable conflict becomes an edge.','Colors can represent available time slots.'],'Build and color a scheduling graph.')])
]};

COURSE.quizzes=COURSE.weeks.map(w=>({week:w.week,topic:w.theme,questions:[
 q(`Which pair belongs most directly to Week ${w.week}: ${w.theme}?`,[`${w.sessions[0].ideas[0]} and ${w.sessions[1].ideas[0]}`,'Unrelated computational topics','Memorizing without application','Skipping verification'],0,`The week develops ${w.sessions[0].ideas[0]} and ${w.sessions[1].ideas[0]}.`,'Remembering','Easy'),
 q(`What is the main purpose of ${w.sessions[0].title}?`,[w.sessions[0].focus,w.sessions[1].focus,'To replace reasoning with memorization','To avoid interpretation'],0,w.sessions[0].focus),
 q(`Which example connects with ${w.sessions[0].title}?`,[w.sessions[0].examples[0],w.sessions[1].examples[0],'A claim with no mathematical connection','An answer with no supporting work'],0,`It illustrates ${w.sessions[0].ideas[0]}.`),
 q(`Which idea is included in ${w.sessions[1].title}?`,[w.sessions[1].ideas[1],w.sessions[0].ideas[1],'Ignoring assumptions','Removing labels and units'],0,`${w.sessions[1].ideas[1]} is a key idea.`),
 q('Which practice supports a defensible mathematical answer?',['Show the representation, process, and verification','Give only the final answer','Change rules after seeing the result','Ignore inconvenient conditions'],0,'A defensible answer makes its reasoning visible.','Applying'),
 q(`Which activity best applies Week ${w.week}?`,[w.sessions[1].tool,w.sessions[0].examples[1],'Copy unrelated formulas','Skip the interpretation'],0,'The stated activity applies the session concepts.','Applying'),
 q('Why state assumptions and conditions?',['They define when a conclusion is valid','They make every answer correct','They remove the need for evidence','They guarantee realism'],0,'Conclusions are meaningful within stated conditions.','Analyzing','Difficult'),
 q('What should follow a completed solution?',['Check it against the question and conditions','Assume it is correct','Remove units','Hide intermediate reasoning'],0,'Verification detects errors and confirms relevance.','Evaluating')
]}));
COURSE.exams=[
 {label:'Examination 1 · Weeks 1–4',weeks:[1,2,3,4]},
 {label:'Examination 2 · Weeks 5–8',weeks:[5,6,7,8]},
 {label:'Examination 3 · Weeks 9–12',weeks:[9,10,11,12]},
 {label:'Examination 4 · Weeks 13–16',weeks:[13,14,15,16]},
 {label:'Final Examination · Weeks 17–18',weeks:[17,18]}
].map((e,i)=>({...e,id:`exam-${i+1}`,questions:e.weeks.flatMap(w=>COURSE.quizzes[w-1].questions.map(x=>({...x,topic:COURSE.quizzes[w-1].topic,week:w})))}));
window.COURSE=COURSE;
