const q=(text,options,answer,rationale,level='Understanding',difficulty='Moderate')=>({text,options,answer,rationale,level,difficulty});
const S=(title,focus,ideas,examples,tool)=>({title,focus,ideas,examples,tool});
const COURSE={
 title:'Mathematics in the Modern World',
 basis:'CHED Mathematics in the Modern World sample syllabus; CMO No. 20, series of 2013',
 weeks:[
 {week:1,theme:'Course Introduction and Mathematical Language',sessions:[
  S('Course Introduction: Mathematics in the Modern World','Explain the scope of CGE103 and recognize mathematics as a language for patterns, relationships, quantities, and decisions.',['Course scope and expectations','Mathematics beyond calculation','Patterns in daily life','Representation and mathematical communication','Responsible reasoning and verification'],['A timetable represents relationships among time, distance, and activity.','A budget uses quantities to support decisions.','A pattern must be described and checked before it is generalized.'],'Orientation activity: identify mathematics used in one ordinary day and explain the information, pattern, or decision involved.'),
  S('Patterns and Mathematical Language','Recognize patterns and translate everyday relationships into clear mathematical symbols and statements.',['Patterns and regularities','Variables and symbols','Expressions and equations','Equality and relationships','Precision in mathematical language'],['“Three more than a number” becomes x+3.','₱250 per person becomes C=250n.','A map scale connects drawing distance with actual distance.'],'Translation activity: write everyday statements in words and symbols, then explain the meaning of each variable.')
 ]},
 {week:2,theme:'Recognizing Patterns and Sequences',sessions:[
  S('Recognizing and Generalizing Patterns','Move from observing visual and numerical patterns to expressing a defensible general rule.',['Visual and numerical patterns','Term position and term value','Constant differences','Recursive descriptions','Explicit descriptions'],['4, 7, 10, 13 has a common difference of 3.','A growing tile design adds one border layer per stage.','A seating row that gains two chairs can be represented by a linear rule.'],'Create a table of term number and term value, describe the change, and test the proposed rule on another term.'),
  S('Sequences and the Fibonacci Pattern','Analyze arithmetic, geometric, and Fibonacci-type sequences without overstating their occurrence in nature.',['Arithmetic sequences','Geometric sequences','Fibonacci recurrence','Ratios of consecutive terms','Responsible pattern claims'],['5, 9, 13, 17 is arithmetic.','3, 6, 12, 24 is geometric.','1, 1, 2, 3, 5 uses the previous two terms.'],'Use spreadsheet formulas to extend sequences, graph their terms, and compare how rapidly they grow.')
 ]},
 {week:3,theme:'Visual Patterns, Symmetry, and Fractals',sessions:[
  S('Visual Patterns and Symmetry','Classify transformations and symmetry in designs, objects, and cultural forms.',['Reflection symmetry','Rotational symmetry','Translation','Tessellation','Symmetry as mathematical structure'],['A bilateral leaf approximates reflection symmetry.','A four-blade fan has rotational symmetry of order four.','A repeated floor tile illustrates translation.'],'Use a diagram or GeoGebra to reflect or rotate a figure and compare corresponding points.'),
  S('Fractals and Growth Patterns in Nature','Explain self-similarity, iteration, and scaling in mathematical and natural patterns.',['Self-similarity','Iteration','Scale changes','Fractal dimension as an extension','Natural forms as approximate fractals'],['The Sierpiński triangle repeats a removal rule.','Fern leaflets approximately resemble the larger frond.','Coastline measurement changes with ruler length.'],'Construct successive stages of a Sierpiński triangle and record how the number and size of pieces change.')
 ]},
 {week:4,theme:'Problem Solving and Reasoning',sessions:[
  S('Inductive and Deductive Reasoning','Use inductive evidence and deductive logic appropriately when forming and justifying conclusions.',['Inductive generalization','Deductive conclusion','Conjecture and counterexample','Premises and validity','Evidence is not proof'],['Observed cases can suggest but not prove a universal rule.','One counterexample disproves a universal claim.','All multiples of 4 are even; 28 is a multiple of 4; therefore 28 is even.'],'Classify short arguments as inductive or deductive, identify premises, and test universal claims with counterexamples.'),
  S('Polya’s Four-Step Problem-Solving Method','Solve unfamiliar problems by understanding, planning, carrying out, and looking back.',['Understand the problem','Devise a plan','Carry out the plan','Look back and verify','Use diagrams, tables, patterns, and simpler cases'],['Draw a diagram before solving a route puzzle.','Organize possible cases in a table instead of guessing.','Check the answer against the original conditions and units.'],'Complete Given, Asked, Representation, Plan, Solution, and Check for one contextual problem.')
 ]},
 {week:5,theme:'Data Management and Descriptive Statistics',sessions:[
  S('Data, Sampling, Frequency Tables, and Bias','Organize data and evaluate variables, samples, distributions, collection quality, and ethics.',['Population and sample','Categorical and numerical variables','Sampling and bias','Frequency and relative-frequency tables','Privacy and consent'],['Course is categorical while age is numerical.','A voluntary online poll can overrepresent strong opinions.','Relative frequencies total 1 or 100%, subject to rounding.'],'Set up one row per observation, build a frequency table, calculate percentages, and verify the total count.'),
  S('Descriptive Statistics and Honest Graphs','Compute and interpret center and spread and choose visualizations that do not mislead.',['Mean, median, and mode','Quartiles and percentiles','Range, variance, and standard deviation','Bar charts, histograms, and line graphs','Axes, scale, and honest interpretation'],['Median is often better for highly skewed income data.','Two groups can share a mean but have different variability.','A truncated axis can exaggerate a small difference.'],'Use spreadsheet statistical functions, create a suitable chart, and justify the chosen measures and scale.')
 ]},
 {week:6,theme:'Geometric Designs',sessions:[
  S('Transformations, Symmetry, and Tessellations','Classify transformations and analyze symmetry and tessellations in art, architecture, and design.',['Translation','Reflection','Rotation','Dilation','Tessellation and symmetry'],['A woven border can repeat by translation.','A four-petal motif may have rotational symmetry of order four.','Regular triangles, squares, and hexagons tessellate the plane.'],'In GeoGebra, construct a motif, transform it, and verify corresponding distances and angles.'),
  S('Geometry in Philippine Art and Design','Apply proportion, scale, symmetry, and geometric structure to a culturally grounded design.',['Proportion and scale','Polygons and angles','Similarity','Geometric motifs in local art','Cultural appreciation with documented sources'],['A floor plan uses a constant scale factor.','A textile motif can combine reflection and translation.','Enlarging lengths by k multiplies areas by k².'],'Create a repeating motif inspired by a documented Philippine design, label transformations, and cite the source.')
 ]},
 {week:7,theme:'Codes and Identification Systems',sessions:[
  S('Modular Arithmetic and Check Digits','Use modular arithmetic to explain identification codes and detect common entry errors.',['Congruence modulo n','Remainders and cycles','Weighted sums','Check digits','Detection versus correction'],['Clock arithmetic works modulo 12.','ISBN and product codes use weighted digit checks.','A valid check digit detects many—but not all—errors.'],'Verify sample ISBN-13 or UPC numbers with a calculator and explain the remainder test.'),
  S('Coding Schemes for Data Transmission','Analyze how coding schemes represent information and add redundancy for reliable transmission.',['Encoding versus encryption','Binary representation','Parity bits','Redundancy','Hamming distance'],['A parity bit can detect an odd number of changed bits.','Binary digits represent states using 0 and 1.','Separated codewords improve error detection.'],'Encode a short message using a provided binary table, add parity, introduce one error, and test detection.')
 ]},
 {week:8,theme:'Cryptography and Privacy',sessions:[
  S('Classical Ciphers and Frequency Analysis','Encrypt, decrypt, and evaluate simple shift and substitution ciphers using modular arithmetic.',['Plaintext and ciphertext','Caesar shift','Substitution cipher','Frequency analysis','Key space and limitations'],['A Caesar shift maps letters modulo 26.','Repeated patterns can reveal a weak cipher.','Encoding a message does not necessarily secure it.'],'Use a cipher wheel to encrypt and decrypt a short phrase, then test a simple frequency attack.'),
  S('Public-Key Ideas, Privacy, and Security','Explain conceptually how mathematical keys support privacy, authentication, and secure communication.',['Symmetric and asymmetric keys','One-way operations','Public and private keys','Authentication and digital signatures','Human security practices'],['A public key may be shared while a private key is protected.','A digital signature supports integrity and authorship.','Strong mathematics cannot compensate for a stolen password.'],'Use envelopes or role cards to simulate public and private information and the mathematical idea of key exchange.')
 ]},
 {week:9,theme:'Linear Programming: Modeling',sessions:[
  S('Variables, Objectives, and Constraints','Translate a resource-allocation situation into a two-variable linear programming model.',['Decision variables','Objective function','Resource constraints','Non-negativity','Assumptions and units'],['Maximize contribution subject to limited labor and materials.','Each constraint bounds feasible decisions.','Every variable needs a clear unit and meaning.'],'Underline decisions, circle resource limits, define variables, then write the objective and constraints.'),
  S('Graphing Inequalities and Feasible Regions','Graph linear inequalities and identify the region satisfying every constraint.',['Boundary lines','Test points','Half-planes','Feasible region','Corner points'],['A solid boundary includes equality.','The feasible region is the intersection of all conditions.','Non-negativity limits solutions to the first quadrant.'],'Use graph paper or Desmos to graph boundaries, test points, shade half-planes, and list feasible vertices.')
 ]},
 {week:10,theme:'Linear Programming: Optimization',sessions:[
  S('The Corner-Point Method','Evaluate an objective at feasible vertices to identify an optimal solution.',['Extreme-point principle','Objective value','Maximum and minimum','Multiple optima','Infeasible and unbounded models'],['Test every feasible corner.','A tie along an edge can create multiple optima.','An optimum is meaningful only under the assumptions.'],'Make a vertex table, substitute into the objective, compare values, and state the solution with units.'),
  S('Evaluating Optimization Models','Assess whether an optimal solution is practical, ethical, and sensitive to changed assumptions.',['Binding constraints','Slack resources','Sensitivity','Integer decisions','Limitations and ethics'],['2.5 buses is not a practical whole-bus decision.','Unused labor is slack, not automatically waste.','Profit models may need safety and fairness constraints.'],'Change one resource limit, resolve the model, and explain which decision changes and why.')
 ]},
 {week:11,theme:'The Mathematics of Finance',sessions:[
  S('Simple and Compound Interest','Compute and compare simple interest, compound interest, present value, and future value.',['Principal and rate','Simple interest I=Prt','Compound amount','Compounding frequency','Nominal and effective rates'],['Six months is 0.5 year with an annual simple rate.','Compound interest earns interest on accumulated balance.','Rates require matching periods for comparison.'],'Calculate simple and compound balances in a spreadsheet and graph their difference.'),
  S('Annuities, Loans, and Investments','Evaluate regular-payment savings and loans using payment, term, future value, and total cost.',['Ordinary annuity and annuity due','Periodic payment','Present and future value','Amortization','Responsible borrowing'],['A lower monthly payment can create greater total repayment.','Payment timing changes annuity value.','Fees belong in loan comparisons.'],'Use PMT or FV with labeled periodic rate and periods; verify signs and total paid.')
 ]},
 {week:12,theme:'Voting and Social Choice',sessions:[
  S('Preference Ballots and Voting Methods','Find election outcomes using plurality, elimination, Borda count, and pairwise comparison.',['Preference schedules','Plurality','Runoff and elimination','Borda count','Pairwise comparison'],['A plurality winner may lack a majority.','Borda uses complete rankings.','Different fair-looking methods can choose different winners.'],'Run a ranked class election and calculate the result under three methods.'),
  S('Fairness Criteria and Voting Paradoxes','Evaluate voting methods using majority, Condorcet, monotonicity, and independence criteria.',['Majority criterion','Condorcet criterion','Monotonicity','Independence of irrelevant alternatives','Arrow’s impossibility insight'],['A Condorcet winner defeats every rival head-to-head.','Removing a loser can alter the winner.','No ranked method satisfies every desirable criterion.'],'Apply two fairness criteria to one preference schedule and record each method’s pass or failure.')
 ]},
 {week:13,theme:'Apportionment and Fair Division',sessions:[
  S('Hamilton’s Method and the Quota Rule','Allocate indivisible seats proportionally using divisors, quotas, and largest remainders.',['Standard divisor','Standard quota','Lower and upper quotas','Hamilton method','Apportionment paradoxes'],['Quotas can be fractional while seats are whole.','Hamilton distributes remaining seats by largest remainders.','Adding a seat can paradoxically cost a group a seat.'],'Calculate quotas, assign lower quotas, rank remainders, and verify the final total.'),
  S('Jefferson, Adams, and Webster Methods','Compare divisor methods and how rounding rules can favor larger or smaller groups.',['Modified divisor','Jefferson rounds down','Adams rounds up','Webster rounds normally','Bias and fairness'],['Changing the divisor changes modified quotas.','Jefferson tends to favor larger groups.','Valid methods can produce different allocations.'],'Apply three divisor methods to the same populations and summarize which groups gain or lose.')
 ]},
 {week:14,theme:'Logic',sessions:[
  S('Propositions, Connectives, and Truth Tables','Represent statements symbolically and find truth values of compound propositions.',['Propositions','Negation','Conjunction and disjunction','Conditional and biconditional','Tautology and contradiction'],['A command is not a proposition.','p∧q is true only when both are true.','p∨¬p is a tautology.'],'Generate all truth rows, add intermediate columns, and evaluate one connective at a time.'),
  S('Equivalence and Valid Arguments','Use equivalence laws and standard argument forms to test validity.',['De Morgan’s laws','Converse, inverse, contrapositive','Modus ponens','Modus tollens','Fallacies and validity'],['A conditional equals its contrapositive.','Affirming the consequent is invalid.','Valid form does not guarantee true premises.'],'Label premises and conclusion, symbolize the form, and test it with a truth table or inference rule.')
 ]},
 {week:15,theme:'The Mathematics of Graphs',sessions:[
  S('Graphs, Networks, Euler Paths, and Circuits','Model connections with vertices and edges and determine whether Euler routes exist.',['Vertices and edges','Degree','Connected graphs','Euler path','Euler circuit'],['Bridges become edges and regions become vertices.','All-even degrees allow an Euler circuit in a connected graph.','Exactly two odd vertices allow an Euler path.'],'Convert a route map into a graph, calculate degrees, and test Euler conditions before tracing.'),
  S('Hamiltonian Circuits and Traveling-Salesperson Problems','Compare routes visiting every vertex and use heuristics for small optimization problems.',['Hamiltonian path and circuit','Weighted graph','Traveling-salesperson problem','Nearest-neighbor heuristic','Heuristics and optimality'],['Hamiltonian routes visit vertices rather than every edge.','Shortest depends on the chosen weights.','Nearest neighbor may miss the best tour.'],'Calculate at least three tours on a small weighted graph and explain whether optimality is proven.')
 ]},
 {week:16,theme:'Trees, Scheduling, and Network Optimization',sessions:[
  S('Trees and Minimum Spanning Trees','Construct low-cost connecting networks using Kruskal’s or Prim’s method.',['Trees and connectedness','No cycles','Spanning trees','Minimum spanning trees','Kruskal and Prim'],['A tree with n vertices has n−1 edges.','A spanning tree connects all locations without cycles.','Kruskal rejects an edge that forms a cycle.'],'Build a minimum spanning tree for a small road, cable, or pipe network and total its cost.'),
  S('Critical-Path Scheduling','Represent dependencies and identify earliest completion and critical activities.',['Activities and precedence','Earliest start and finish','Latest start and finish','Slack','Critical path'],['Delaying a critical activity delays the project.','Parallel activities can happen together.','The longest dependency path determines minimum time.'],'Draw a task network, calculate path lengths, and identify the critical path.')
 ]},
 {week:17,theme:'Mathematical Systems',sessions:[
  S('Axioms, Definitions, and Mathematical Systems','Explain systems built from undefined terms, definitions, axioms, and theorems.',['Undefined terms','Definitions','Axioms and postulates','Theorems and proofs','Consistency'],['Point and line may be undefined terms.','A theorem follows from axioms and prior results.','Changing an axiom can create a different system.'],'Create a small rule-based world, list primitive terms and axioms, then derive two consequences.'),
  S('Modular Systems and Alternative Geometries','Operate in modular systems and compare conclusions under altered assumptions.',['Closure and operations','Modular arithmetic','Finite systems','Euclidean parallel postulate','Non-Euclidean alternatives'],['In modulo 5, 3+4 is congruent to 2.','Clock arithmetic is finite and modular.','Spherical geometry has no Euclidean parallel lines.'],'Complete operation tables modulo n and test closure, identity, and inverses.')
 ]},
 {week:18,theme:'Integration and Mathematical Citizenship',sessions:[
  S('Integrated Mathematics in Modern Decisions','Combine suitable tools to address a realistic decision involving data, fairness, cost, or networks.',['Match representation to question','State assumptions','Verify computations','Compare alternatives fairly','Communicate uncertainty'],['Allocate resources using data and a stated fairness rule.','Compare loans by effective cost.','Plan a network balancing cost, access, and constraints.'],'Organize a capstone into Data, Model, Computation, Verification, Recommendation, and Limitations.'),
  S('Capstone Presentation and Course Synthesis','Defend a mathematical recommendation clearly, ethically, and for the intended audience.',['Claim–evidence–reasoning','Readable tables and visuals','Accuracy and reproducibility','Ethical disclosure','Mathematics as a way of knowing'],['Lead with the recommendation and support it.','Label units, sources, scales, and assumptions.','Acknowledge uncertainty rather than false precision.'],'Test every calculation, cite sources, explain the method, disclose limitations, and prepare for questions.')
 ]}
 ],quizzes:[]
};

const QUIZ_SEEDS=[
 ['Mathematics in Our World','Which best describes mathematics in modern life?',['Only rapid calculation','A language and tool for patterns, relationships, and decisions','A way to remove all uncertainty','A subject used only in science'],1],
 ['Patterns and Sequences','Which rule generates 5, 9, 13, 17, …?',['Add 4','Multiply by 4','Add consecutive integers','Double then subtract 1'],0],
 ['Symmetry and Fractals','Which feature defines rotational symmetry?',['The figure matches itself after a turn smaller than 360°','Both halves merely have equal area','Its boundary is irregular','It occurs in nature'],0],
 ['Reasoning and Problem Solving','What disproves a universal mathematical claim?',['Many supporting examples','One valid counterexample','A calculator result','A diagram alone'],1],
 ['Data Management and Statistics','Which measure resists an extreme outlier best?',['Mean','Median','Range','Standard deviation'],1],
 ['Geometric Designs','Which rigid motion turns a figure about a fixed point?',['Dilation','Rotation','Stretching','Projection'],1],
 ['Codes','What is a check digit mainly used for?',['Compression','Detection of common entry errors','Encryption','Identity proof'],1],
 ['Cryptography','Which statement is correct?',['Encoding and encryption are identical','Encryption protects meaning with a key','Encoding always needs a secret key','Ciphers never use mathematics'],1],
 ['Linear Programming Models','What is the feasible region?',['One boundary','Solutions satisfying every constraint','Objective intercepts only','Integer points only'],1],
 ['Linear Programming Optimization','Where is the objective tested in the corner-point method?',['Every plane point','Feasible vertices','Only the origin','Only x=y'],1],
 ['Financial Mathematics','What distinguishes compound interest?',['No rate is used','Prior interest can also earn interest','It always costs less','Principal is ignored'],1],
 ['Voting','Which method assigns points to ranked positions?',['Plurality','Borda count','Random choice','Simple majority'],1],
 ['Apportionment','What is assigned first in Hamilton’s method?',['Upper quotas','Lower quotas','Random seats','Seats to the smallest group'],1],
 ['Logic','When is p∧q true?',['At least one true','Both true','Both false','p false'],1],
 ['Graph Theory','When does a connected graph have an Euler circuit?',['Every vertex has even degree','Exactly two odd vertices','All weights are equal','It has no cycle'],0],
 ['Network Optimization','What does a minimum spanning tree minimize?',['Vertices','Total edge weight while connecting all vertices','Every degree','Possible paths'],1],
 ['Mathematical Systems','What can happen if an axiom changes?',['Mathematics becomes invalid','A different consistent system may result','Every theorem stays unchanged','Definitions disappear'],1],
 ['Course Integration','What supports ethical mathematical communication?',['Hide assumptions','Report only percentages','State sources, units, assumptions, and limitations','Use maximum decimals'],2]
];
COURSE.quizzes=QUIZ_SEEDS.map((seed,i)=>{const [topic,text,options,answer]=seed;return{week:i+1,topic,questions:[
 q(text,options,answer,'The correct option matches the defining idea taught in this week.'),
 q('What is the strongest first step?',['Calculate immediately','Clarify the question, information, units, and conditions','Remove inconvenient information','Choose the longest formula'],1,'Clear quantities and conditions guide the method.','Applying','Easy'),
 q('Which result needs the most careful interpretation?',['A value with unit and source','A result checked another way','A number without base, unit, or context','A transparent estimate'],2,'A context-free number cannot be evaluated responsibly.','Analyzing'),
 q('A surprising answer appears. What should happen next?',['Submit it','Replace it','Check inputs, method, units, and reasonableness','Delete the work'],2,'Verification locates setup, computation, unit, or interpretation errors.','Evaluating'),
 q('Which action uses a digital tool responsibly?',['Treat output as proof','Estimate, enter carefully, verify, and interpret','Add decimals regardless of data','Let the tool define the question'],1,'The user remains responsible for mathematical meaning.','Understanding','Easy')
]};});
COURSE.exams=[
 {label:'Preliminary Examination · Weeks 1–6',weeks:[1,2,3,4,5,6]},
 {label:'Midterm Examination · Weeks 7–12',weeks:[7,8,9,10,11,12]},
 {label:'Final Examination · Weeks 13–18',weeks:[13,14,15,16,17,18]}
].map((e,i)=>({...e,id:`exam-${i+1}`,questions:e.weeks.flatMap(w=>COURSE.quizzes[w-1].questions.map(x=>({...x,topic:COURSE.quizzes[w-1].topic,week:w})))}));
window.COURSE=COURSE;
