const params=new URLSearchParams(location.search),weekNo=Math.min(18,Math.max(1,+params.get('week')||1)),sessionNo=Math.min(2,Math.max(1,+params.get('session')||1));
const week=COURSE.weeks[weekNo-1],s=week.sessions[sessionNo-1],deck=document.querySelector('#deck');document.title=`Week ${weekNo} Session ${sessionNo} · ${s.title}`;
const esc=x=>String(x).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const bullets=a=>`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const conceptExplanation=(idea,i)=>{
 const example=s.examples[i%s.examples.length];
 return `<p class="lead"><strong>${esc(idea)}</strong> is an essential part of today’s lesson. Understand what it means, identify the conditions where it applies, and connect it to this example: <em>${esc(example)}</em></p>`;
};
const workedSteps=[
 `Identify the mathematical idea involved: ${s.ideas[0]}.`,
 'Separate the given information from the quantity, conclusion, or decision being requested.',
 'Choose a suitable representation such as a statement, table, diagram, graph, formula, or network.',
 'Apply the rule carefully, keeping labels, units, conditions, and intermediate results visible.',
 'Interpret the result in a complete sentence and check whether it is reasonable in the original situation.'
];
const slides=[];
const add=(cls,html)=>slides.push(`<section class="slide ${cls}" data-number="${slides.length+1}">${html}</section>`);
add('cover',`<div><p class="kicker">Week ${weekNo} · Session ${sessionNo}</p><h1>${esc(s.title)}</h1><p class="lead">${esc(week.theme)}</p></div>`);
add('slide-title',`<div><p class="kicker">Learning outcomes</p><h2>At the end of this session</h2></div>${bullets([`Explain the meaning of ${s.ideas[0]} and ${s.ideas[1]}.`,s.focus,'Apply the lesson to a new situation and justify the result.'])}`);
add('two-col',`<div><p class="kicker">Opening prompt</p><h2>Where does this appear in daily life?</h2><p class="lead">Think of one decision, object, post, transaction, or route that uses today’s idea.</p></div><div class="panel"><strong>Think · Pair · Share</strong>${bullets(['Think independently for one minute.','Explain your example to a partner.','Identify the mathematical information involved.'])}</div>`);
add('slide-title',`<div><p class="kicker">Activate prior knowledge</p><h2>What do we already know?</h2></div>${bullets(['What words or symbols are familiar?','What could be measured, compared, or classified?','What mistake might someone easily make?'])}`);
add('slide-title',`<div><p class="kicker">Concept map</p><h2>Five ideas guide this session</h2></div>${bullets(s.ideas)}`);
s.ideas.forEach((idea,i)=>add(i%2?'two-col':'slide-title',i%2?`<div><p class="kicker">Key concept ${i+1} of 5</p><h2>${esc(idea)}</h2>${conceptExplanation(idea,i)}</div><div class="panel"><strong>Understand the concept</strong>${bullets(['State the idea in your own words.','Identify the information needed to use it.','Explain why the example fits the definition.','Give one non-example or common misuse.'])}</div>`:`<div><p class="kicker">Key concept ${i+1} of 5</p><h2>${esc(idea)}</h2></div>${conceptExplanation(idea,i)}${bullets(['Meaning: explain the idea before applying a procedure.','Representation: connect words with symbols, diagrams, tables, or graphs.','Interpretation: relate every result to the original situation.'])}`));
add('two-col',`<div><p class="kicker">Example 1</p><h2>Read the situation carefully</h2><div class="example">${esc(s.examples[0])}</div></div><div class="panel"><strong>Before solving</strong>${bullets(['Identify given information.','State what must be found.','Keep units and conditions visible.'])}</div>`);
add('slide-title',`<div><p class="kicker">Worked example · solution process</p><h2>From information to a justified answer</h2></div><ol>${workedSteps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`);
add('two-col',`<div><p class="kicker">Worked example · interpretation</p><h2>What the result means</h2><div class="example">${esc(s.examples[0])}</div></div><div class="panel"><strong>A complete answer must include</strong>${bullets(['The computed or logical result','The correct unit, label, or truth condition','A sentence connected to the question','One reason the result is reasonable'])}</div>`);
add('check',`<div><p class="kicker">Pause and check</p><h2>Does the result make sense?</h2></div>${bullets(['Estimate the expected size or direction.','Check the unit and base of comparison.','Try an alternate representation or reverse operation.'])}`);
add('two-col',`<div><p class="kicker">Example 2 · comparison</p><h2>Compare, do not merely calculate</h2><div class="example">${esc(s.examples[1])}</div></div><div class="panel"><strong>Analyze the example</strong>${bullets(['What information is changing?','What remains fixed?','Which concept from the lesson applies?','What conclusion is supported?'])}</div>`);
add('slide-title',`<div><p class="kicker">Common mistakes</p><h2>A plausible-looking answer can still be wrong</h2></div>${bullets([`Using ${s.ideas[0]} without checking its definition or conditions`,'Substituting values before identifying what each quantity represents','Ignoring units, reference groups, constraints, direction, or scale','Treating a digital output as an explanation','Giving an answer without interpreting or verifying it'])}`);
add('two-col',`<div><p class="kicker">Multiple representations</p><h2>Show the same idea another way</h2><p class="lead">Words, symbols, tables, graphs, and diagrams emphasize different features.</p></div><div class="panel">${bullets(['Words explain meaning.','Symbols show structure.','Tables organize cases.','Graphs reveal shape and change.'])}</div>`);
add('two-col',`<div><p class="kicker">Example 3 · critical interpretation</p><h2>What can—and cannot—be concluded?</h2><div class="example">${esc(s.examples[2])}</div></div><div class="panel"><strong>Write two statements</strong>${bullets(['One conclusion directly supported by the information','One tempting conclusion that the information does not justify'])}</div>`);
add('slide-title',`<div><p class="kicker">Digital application</p><h2>Use technology with mathematical control</h2></div><p class="lead">${esc(s.tool)}</p>`);
add('activity',`<div><p class="kicker">Walkthrough · Step 1</p><h2>Prepare the information</h2></div>${bullets(['Open the specified tool and start a clean file or page.','Label every input, column, axis, or object before entering values.','Record the source, date, and unit when data are external.'])}`);
add('activity',`<div><p class="kicker">Walkthrough · Step 2</p><h2>Build the representation</h2></div>${bullets(['Enter a small test case first.','Use references, formulas, or construction tools deliberately.','Check one result manually before copying or automating.'])}`);
add('activity',`<div><p class="kicker">Walkthrough · Step 3</p><h2>Verify and communicate</h2></div>${bullets(['Change one input and predict the effect before observing it.','Inspect labels, scale, rounding, and formatting.','Write the conclusion beside the output—not only in your head.'])}`);
add('two-col activity',`<div><p class="kicker">Guided practice</p><h2>Apply the lesson step by step</h2><p class="lead">Create a new situation similar to “${esc(s.examples[1])}” but change one important value, condition, or category.</p></div><div class="panel">${bullets(['1. List the given information and target.','2. Select and name the concept used.','3. Show the representation and complete solution.','4. Interpret and verify the answer.'])}</div>`);
add('activity',`<div><p class="kicker">Independent practice</p><h2>Solve and explain</h2></div>${bullets([`Use ${s.ideas[0]} and ${s.ideas[1]} in one original example.`,'Show every necessary step or relationship.','Write the final conclusion in words.','Identify one assumption or limitation.'])}`);
add('two-col activity',`<div><p class="kicker">Collaborative task</p><h2>Create and exchange a problem</h2><p class="lead">In pairs, write a realistic situation using today’s concept. Exchange, solve, and give one precision-focused comment.</p></div><div class="panel"><strong>Success criteria</strong>${bullets(['Solvable with supplied information','Correct use of concept and units','Clear and defensible interpretation'])}</div>`);
add('check',`<div><p class="kicker">Independent check</p><h2>Explain without the slide</h2></div>${bullets([`Define “${s.ideas[0]}” in your own words.`,`Use “${s.ideas[1]}” in a new example.`,`Name one error that careful checking prevents.`])}`);
add('slide-title',`<div><p class="kicker">Exit ticket</p><h2>Three sentences before you leave</h2></div>${bullets(['Today I learned that…','A result should be checked by…','I can apply this when…'])}`);
add('summary',`<div><p class="kicker">Session synthesis</p><h2>What you should remember</h2><p class="lead">${esc(s.focus)}</p></div>${bullets(s.ideas)}`);
add('cover',`<div><p class="kicker">Next step</p><h1>Practice, verify, explain.</h1><p class="lead">Complete the weekly quiz after both sessions. Keep your working and interpretations.</p></div>`);
if(weekNo===4&&sessionNo===1){
 const actual=[
 ['cover','<div><p class="kicker">Week 4 · Session 1</p><h1>Inductive and Deductive Reasoning</h1><p class="lead">From observations to reliable mathematical conclusions</p></div>'],
 ['slide-title','<div><p class="kicker">Learning outcomes</p><h2>What you will learn</h2></div><ul><li>Differentiate inductive and deductive reasoning.</li><li>Form and test a conjecture.</li><li>Disprove a universal claim with a counterexample.</li><li>Identify premises and conclusions.</li><li>Judge whether an argument is valid.</li></ul>'],
 ['two-col','<div><p class="kicker">Opening pattern</p><h2>What comes next?</h2><div class="example">2, 6, 12, 20, 30, ___</div></div><div class="panel"><p>Differences are 4, 6, 8, 10.</p><p>The next difference may be 12.</p><p><strong>Prediction: 42.</strong></p><p>A prediction supported by a pattern is not yet proof.</p></div>'],
 ['slide-title','<div><p class="kicker">Reasoning</p><h2>Mathematics is more than calculation</h2></div><p class="lead">Reasoning explains why a claim should be accepted. It connects evidence or premises to a conclusion and reveals when information is insufficient.</p>'],
 ['slide-title','<div><p class="kicker">An argument</p><h2>Premises support a conclusion</h2></div><div class="example">Premise 1: All squares have four sides.<br>Premise 2: Figure A is a square.<br>Conclusion: Figure A has four sides.</div>'],
 ['two-col','<div><p class="kicker">Comparison</p><h2>Two forms of reasoning</h2></div><div class="panel"><p><strong>Inductive:</strong> specific observations → probable general claim.</p><p><strong>Deductive:</strong> accepted rule → necessary specific conclusion.</p><p>Induction discovers patterns; deduction proves or applies rules.</p></div>'],
 ['slide-title','<div><p class="kicker">Inductive reasoning</p><h2>Observation → pattern → conjecture</h2></div><p class="lead">Inductive reasoning examines particular cases and proposes a general rule. More evidence can strengthen the conjecture, but examples alone do not make it certain.</p>'],
 ['two-col','<div><p class="kicker">Example</p><h2>3, 7, 11, 15, 19, …</h2></div><div class="panel"><ol><li>Observe a constant increase of 4.</li><li>Conjecture: add 4 each time.</li><li>Predict the next term: 23.</li></ol></div>'],
 ['two-col','<div><p class="kicker">Visual pattern</p><h2>Growing tiles</h2><div class="example">Stage 1: 3<br>Stage 2: 5<br>Stage 3: 7</div></div><div class="panel"><p>The design adds 2 tiles per stage.</p><p>Possible rule: T(n)=2n+1.</p><p>Check the rule against every supplied stage.</p></div>'],
 ['slide-title','<div><p class="kicker">Conjecture</p><h2>A claim waiting to be tested</h2></div><ul><li>State the proposed rule precisely.</li><li>Test new cases beyond the original examples.</li><li>Search for a case that fails.</li><li>Prove the rule deductively or revise it.</li></ul>'],
 ['two-col','<div><p class="kicker">Counterexample</p><h2>One case can disprove “all”</h2></div><div class="panel"><p><strong>Claim:</strong> All prime numbers are odd.</p><p><strong>Counterexample:</strong> 2 is prime and even.</p><p><strong>Therefore:</strong> the universal claim is false.</p></div>'],
 ['check','<div><p class="kicker">Try it</p><h2>Disprove the claim</h2></div><p class="lead">“Squaring a number always makes it greater.”</p><p>Test x=1/2: x²=1/4, and 1/4&lt;1/2. Therefore, x=1/2 is a counterexample.</p>'],
 ['slide-title','<div><p class="kicker">Deductive reasoning</p><h2>Rules → necessary conclusion</h2></div><p class="lead">If an argument has a valid form and true premises, its conclusion must be true. Deduction is the basis of mathematical proof.</p>'],
 ['two-col','<div><p class="kicker">Deductive example</p><h2>Apply a general rule</h2></div><div class="panel"><p>All multiples of 4 are even.</p><p>28 is a multiple of 4.</p><p><strong>Therefore, 28 is even.</strong></p></div>'],
 ['two-col','<div><p class="kicker">Geometry example</p><h2>Find the missing angle</h2></div><div class="panel"><p>Triangle angles total 180°.</p><p>Given: 55° and 65°.</p><p>180°−55°−65°=60°.</p><p><strong>The third angle is 60°.</strong></p></div>'],
 ['slide-title','<div><p class="kicker">Validity</p><h2>Does the conclusion logically follow?</h2></div><p class="lead">A valid argument cannot have all true premises and a false conclusion. Validity concerns structure; truth concerns the accuracy of the statements.</p>'],
 ['two-col','<div><p class="kicker">Valid form</p><h2>Modus ponens</h2><div class="formula-big">If p→q<br>p<br>∴ q</div></div><div class="panel"><p>If a number is divisible by 10, it ends in 0.</p><p>350 is divisible by 10.</p><p>Therefore, 350 ends in 0.</p></div>'],
 ['two-col','<div><p class="kicker">Invalid form</p><h2>Affirming the consequent</h2></div><div class="panel"><p>If it rains, the road is wet.</p><p>The road is wet.</p><p>Therefore, it rained.</p><p><strong>Invalid:</strong> a sprinkler could also wet the road.</p></div>'],
 ['slide-title','<div><p class="kicker">Sound argument</p><h2>Valid form + true premises</h2></div><ul><li>First check whether the conclusion follows.</li><li>Then check whether the premises are true.</li><li>A sound argument satisfies both requirements.</li></ul>'],
 ['two-col','<div><p class="kicker">Classify A</p><h2>The next bus will be late</h2><div class="example">The last five buses were late, so the next bus will probably be late.</div></div><div class="panel"><strong>Inductive</strong><p>The conclusion is a probability based on observed cases.</p></div>'],
 ['two-col','<div><p class="kicker">Classify B</p><h2>A rectangle property</h2><div class="example">All rectangles have four right angles. R is a rectangle. Therefore R has four right angles.</div></div><div class="panel"><strong>Deductive</strong><p>A definition is applied to a specific case.</p></div>'],
 ['activity','<div><p class="kicker">Guided practice</p><h2>Classify and justify</h2></div><ol><li>1,4,9,16 suggests the next term is 25.</li><li>All even integers are divisible by 2; 86 is even; therefore 86 is divisible by 2.</li><li>The first four tested products are positive, so the next one will be positive.</li></ol>'],
 ['activity','<div><p class="kicker">Answers</p><h2>Check the reasoning</h2></div><ol><li>Inductive—pattern-based prediction.</li><li>Deductive—general rule applied to 86.</li><li>Inductive—conclusion based on tested cases.</li></ol>'],
 ['check','<div><p class="kicker">Independent practice</p><h2>Show your reasoning</h2></div><ol><li>Give a counterexample: “All numbers divisible by 3 are odd.”</li><li>Write one inductive argument from daily life.</li><li>Write one deductive argument and label its premises.</li><li>Explain why many examples are not a proof.</li></ol>'],
 ['summary','<div><p class="kicker">Summary</p><h2>What you should remember</h2></div><ul><li>Induction produces probable conjectures from observations.</li><li>Deduction produces necessary conclusions from premises.</li><li>One counterexample disproves a universal claim.</li><li>Validity is about logical structure.</li><li>Soundness requires validity and true premises.</li></ul>'],
 ['cover','<div><p class="kicker">Exit ticket</p><h1>Observation or proof?</h1><p class="lead">Write one inductive and one deductive argument. Label the evidence or premises and the conclusion.</p></div>']
 ];
 slides.length=0;actual.forEach(x=>add(x[0],x[1]));
}
deck.innerHTML=slides.join('');
let current=0;const els=[...document.querySelectorAll('.slide')],counter=document.querySelector('#counter');function show(n){current=(n+els.length)%els.length;els.forEach((e,i)=>e.classList.toggle('active',i===current));counter.textContent=`${current+1} / ${els.length}`;history.replaceState(null,'',`?week=${weekNo}&session=${sessionNo}#${current+1}`)}
document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelector('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();addEventListener('keydown',e=>{if(['ArrowRight',' ','PageDown'].includes(e.key))show(current+1);if(['ArrowLeft','PageUp'].includes(e.key))show(current-1);if(e.key==='Home')show(0);if(e.key==='End')show(els.length-1)});show(Math.max(0,(+location.hash.slice(1)||1)-1));
